[defaults]
# global page offset
page_offset = 0
# global minimum length
min_len = 3

# input folder
input_prefix = "input"
# output folder
output_prefix = "output"
# output file name append
output_suffix = ".bookmarked.pdf"

[[tasks]]
# input file name. relative to input_prefix
input_file = "book1.pdf"
toc = """
第一章 绪论
1.1 引言
1.2 数学分析的基本概念
1.3 数学分析的基本定理
1.4 数学分析的基本方法
1.5 数学分析的应用
1.6 数学分析的发展历史
"""
page_offset = 10
min_len = 2
