name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./gradlew.bat build distZip --no-daemon
          else
            ./gradlew build distZip --no-daemon
          fi

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-bookmark-${{ runner.os }}
          path: build/distributions/*.zip
          retention-days: 30