name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        if: "hashFiles('**/pom.xml') != ''"
        run: mvn -B -ntp -DskipTests verify

      - name: Set up Gradle cache
        if: "hashFiles('**/build.gradle*') != '' && hashFiles('**/pom.xml') == ''"
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        if: "hashFiles('**/build.gradle*') != '' && hashFiles('**/pom.xml') == ''"
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew build --no-daemon
          else
            gradle build --no-daemon
          fi